[[redirects]]
  from = "/ativar"
  to = "/ativar.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "https://github.com/qjunior100/QLicitacoes/releases/download/1.0/QLicitacoes_V1.0.zip"
  status = 301

[build]
  publish = "."

[[redirects]]
  from = "/afiliados"
  to = "/afiliados.html"
  status = 200
