[[redirects]]
  from = "/ativar"
  to = "/ativar.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "https://github.com/qjunior100/QLicitacoes/releases/download/1.3/QLicitacoes_V1.3.zip"
  status = 301

[build]
  publish = "."

[[redirects]]
  from = "/afiliados"
  to = "/afiliados.html"
  status = 200

[[redirects]]
  from = "/instrucoes"
  to = "/instrucoes.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200