[[redirects]]
  from = "/ativar"
  to = "/ativar.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "/ativar.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
